SET FAOITEM /"Area harvested",Yield,Production/;

PARAMETERS
FAODATA(REGION,FAOITEM,HISTORY,CROP)
CROPMIX_Data(REGION,HISTORY,CROP) in million hectares
;
FAODATA(REGION,FAOITEM,HISTORY,CROP)=0;

Execute "csv2gdx FAOSTAT_data_3-8-2019.csv ID=FAODATA UseHeader=yes INDEX=(2,3,5,4) Value=7";
Execute_Load "FAOSTAT_data_3-8-2019.gdx" FAODATA;

CROPMIX_Data(REGION,HISTORY,CROP)
 = FAODATA(REGION,"Area harvested",HISTORY,CROP)/1000000;

DISPLAY CROPMIX_Data;